name: repo-checks

on:
  pull_request:
    branches:
    - master

jobs:
  react:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - task: Lint
            allow_failures: false
            command: yarn workspace app_scaffold lint
          - task: Test
            allow_failures: false
            command: yarn workspace app_scaffold test
    steps:
    - uses: zendesk/checkout@v2
    - name: Use Node.js
      uses: zendesk/setup-node@v2.1.2
      with:
        node-version: '12.x'
    - name: install packages
      run: yarn install
    - name: ${{ matrix.env.TASK }}
      run: TASK=${{ matrix.env.TASK }} ${{ matrix.command }}